# Generated by Django 4.1.3 on 2022-11-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='contents',
        ),
        migrations.AlterField(
            model_name='article',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
