# Generated by Django 4.1.3 on 2022-11-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrydata',
            old_name='country',
            new_name='county',
        ),
    ]
